# Generated by Django 4.2.3 on 2023-09-09 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StudenntForm',
            new_name='Student',
        ),
    ]
